In [2]:
import pandas as pd
import openpyxl

In [7]:
path = r"H:\Python\3°etapa\PY-MA\Aula 4  - População 1,5 ponto\CD2022_Populacao_2010_Compatibilizada_20231222.xlsx"

In [8]:
tabela = pd.read_excel(path, header=None)

In [9]:
tabela

,0,1,2,3,4,5,6,7
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Censo Demográfico 2022: População e Domicílios...,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022
3,NaN,RO,11,00015,Alta Floresta D'Oeste,24392,24392,21494
4,NaN,RO,11,00023,Ariquemes,90353,90353,96833
...,...,...,...,...,...,...,...,...
5572,NaN,DF,53,00108,Brasília,2570160,2572159,2817381
5573,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5574,NaN,Nota: Para o cálculo das taxas de crescimento ...,NaN,NaN,NaN,NaN,NaN,NaN
5575,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5576,NaN,Fonte: IBGE. Diretoria de Pesquisas - DPE - C...,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
tabela_tratada = tabela.iloc[3:5573, 1:8].copy()

In [11]:
tabela_tratada

       1   2      3                      4        5        6        7
3     RO  11  00015  Alta Floresta D'Oeste    24392    24392    21494
4     RO  11  00023              Ariquemes    90353    90353    96833
5     RO  11  00031                 Cabixi     6313     6313     5351
6     RO  11  00049                 Cacoal    78574    78574    86887
7     RO  11  00056             Cerejeiras    17029    17029    15890
...   ..  ..    ...                    ...      ...      ...      ...
5568  GO  52  22005             Vianópolis    12548    12548    14956
5569  GO  52  22054         Vicentinópolis     7371     7373     8768
5570  GO  52  22203               Vila Boa     4735     4735     4215
5571  GO  52  22302          Vila Propício     5145     5145     5815
5572  DF  53  00108               Brasília  2570160  2572159  2817381

[5570 rows x 7 columns]

In [12]:
tabela_tratada.columns = [
    "UF",
    "COD_UF",
    "COD_MUNIC",
    "Municipio",
    "População Município 2010",
    "População 2010 (Alterações de Limites até 2022)",
    "População Censo 2022"
]

In [13]:
estado = ["AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO"]

estados = tabela_tratada[tabela_tratada["UF"].isin(estado)]

In [14]:
estados["UF"].unique()

<StringArray>
['RO', 'AC', 'AM', 'RR', 'PA', 'AP', 'TO', 'MA', 'PI', 'CE', 'RN', 'PB', 'PE',
 'AL', 'SE', 'BA', 'MG', 'ES', 'RJ', 'SP', 'PR', 'SC', 'RS', 'MS', 'MT', 'GO',
 'DF']
Length: 27, dtype: str

In [16]:
pop_estado = (
    estados.groupby(["UF"], as_index=False)
      .agg(
          populacao_2010=("População Município 2010", "sum"),
          populacao_2022=("População Censo 2022", "sum"),
      )
)

In [19]:
pop_estado.dtypes

UF                    str
populacao_2010    float64
populacao_2022    float64
dtype: object

In [18]:

pop_estado["populacao_2010"] = pop_estado["populacao_2010"].astype(float).dropna()
pop_estado["populacao_2022"] = pop_estado["populacao_2022"].astype(float).dropna()

In [20]:
pop_estado["DIF"] = pop_estado["populacao_2022"] - pop_estado["populacao_2010"]

In [21]:
pop_estado

    UF  populacao_2010  populacao_2022        DIF
0   AC        733559.0        830018.0    96459.0
1   AL       3120494.0       3127683.0     7189.0
2   AM       3483985.0       3941613.0   457628.0
3   AP        669526.0        733759.0    64233.0
4   BA      14016906.0      14141626.0   124720.0
5   CE       8452381.0       8794957.0   342576.0
6   DF       2570160.0       2817381.0   247221.0
7   ES       3514952.0       3833712.0   318760.0
8   GO       6003788.0       7056495.0  1052707.0
9   MA       6574789.0       6776699.0   201910.0
10  MG      19597330.0      20539989.0   942659.0
11  MS       2449024.0       2757013.0   307989.0
12  MT       3035122.0       3658649.0   623527.0
13  PA       7581051.0       8120131.0   539080.0
14  PB       3766528.0       3974687.0   208159.0
15  PE       8796448.0       9058931.0   262483.0
16  PI       3118360.0       3271199.0   152839.0
17  PR      10444526.0      11444380.0   999854.0
18  RJ      15989929.0      16055174.0    65245.0
19  RN       3168027.0       3302729.0   134702.0
20  RO       1562409.0       1581196.0    18787.0
21  RR        450479.0        636707.0   186228.0
22  RS      10693929.0      10882965.0   189036.0
23  SC       6248436.0       7610361.0  1361925.0
24  SE       2068017.0       2210004.0   141987.0
25  SP      41262199.0      44411238.0  3149039.0
26  TO       1383445.0       1511460.0   128015.0

In [23]:
pop_estado.to_csv(r"H:\Python\3°etapa\PY-MA\Aula 4  - População 1,5 ponto.csv")